apiVersion: v1
kind: Secret
metadata:
  name: sidecar-config
type: Opaque
stringData:
  HOOP_SIDECAR_CONFIG: '{{ if include "hoopsidecar.hasConfigFile" . }}{{ include "hoopsidecar.configPath" . }}{{ end }}'
  HOOP_LICENSE: '{{ .Values.license | default "" }}'
  HOOP_CONTROL_PLANE_URL: '{{ .Values.controlPlane.url | default "" }}'
  HOOP_SIDECAR_TOKEN: '{{ .Values.controlPlane.token | default "" }}'
