//go:build darwin

package service

// This file holds the LaunchDaemon plist template and the helper that
// renders it. Kept separate from service_darwin.go so the plist's keys —
// conventions, not code — can be reviewed together, mirroring the split
// between unit_linux.go and service_linux.go.

import (
	"bytes"
	"fmt"
	"html"
	"strings"
	"text/template"
)

// plistTemplate is the canonical hsh-tunneld LaunchDaemon. It is written
// to /Library/LaunchDaemons/dev.hoop.hsh-tunneld.plist at install time.
//
// Design notes:
//
//   - Label — must equal the file's basename without .plist and the
//     launchctl target's last component. We template it from the same
//     constant the manager uses so the two never drift.
//
//   - ProgramArguments — launchd's argv. We pass exactly the flags the
//     systemd unit's ExecStart passes: --config-file, --ipc-socket,
//     --ipc-group. The daemon validates its config at startup and exits
//     non-zero on a bad config, so a launchd-managed run gets the same
//     fail-fast behaviour the systemd ExecStartPre gives us, with the
//     diagnostic captured in StandardErrorPath below. (launchd has no
//     ExecStartPre; wrapping the daemon in a shell just to re-run
//     validate-config would add a process for no behavioural gain.)
//
//   - RunAtLoad + KeepAlive(SuccessfulExit=false) — the launchd analogue
//     of systemd's Restart=on-failure: start at load, restart on a
//     crash/non-zero exit, but stay down after a clean `launchctl bootout`
//     or an explicit exit 0. We deliberately do NOT use KeepAlive=true
//     (restart-always) for the same reason the unit avoids
//     Restart=always: a deliberate stop must actually stop the daemon.
//
//   - ThrottleInterval=2 — matches systemd's RestartSec=2; launchd's
//     default 10s back-off would make a transient gateway outage feel
//     like a hang.
//
//   - UserName=root / GroupName=wheel — the daemon needs root to open the
//     utun device and to mutate the host route table + /etc/resolver,
//     exactly like the Linux unit runs as root. The hsh group governs
//     access to the IPC socket and is applied by the daemon itself
//     (--ipc-group), not by launchd, because launchd only sets the
//     process's primary group, not supplementary groups.
//
//   - ProcessType=Interactive — tells launchd this is a foreground-style
//     service that should not be aggressively throttled/suspended like a
//     background batch job. The tunnel must stay responsive on the data
//     path.
//
//   - Standard{Out,Error}Path — launchd has no journal, so we point logs
//     at /var/log. Operators tail these the way they'd
//     `journalctl -u hsh-tunneld -f` on Linux.
//
// {{.SocketPath}} / {{.ConfigPath}} / {{.GroupName}} mirror the Options
// fields so an operator who overrides them at install time gets a
// consistent plist.
const plistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- hsh-tunneld LaunchDaemon. Generated by 'hsh-tunneld install' — do not
     edit by hand. Re-run 'sudo hsh-tunneld install' to refresh, or
     'sudo hsh-tunneld uninstall' to remove. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{{.Label}}</string>

    <key>ProgramArguments</key>
    <array>
        <string>{{.BinaryPath}}</string>
        <string>--config-file</string>
        <string>{{.ConfigPath}}</string>
        <string>--ipc-socket</string>
        <string>{{.SocketPath}}</string>
        <string>--ipc-group</string>
        <string>{{.GroupName}}</string>
    </array>

    <key>UserName</key>
    <string>root</string>
    <key>GroupName</key>
    <string>wheel</string>

    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>2</integer>

    <key>ProcessType</key>
    <string>Interactive</string>

    <key>StandardOutPath</key>
    <string>/var/log/hsh-tunneld.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/hsh-tunneld.log</string>
</dict>
</plist>
`

// renderPlist returns the rendered LaunchDaemon plist body for the given
// Options. Pure (no disk writes) so tests can diff the output. The values
// are XML-escaped because plist string values are XML text; a path with
// an `&` (legal on macOS) would otherwise produce a malformed plist that
// launchd refuses to load.
func renderPlist(opts Options) (string, error) {
	tmpl, err := template.New("hsh-tunneld.plist").Parse(plistTemplate)
	if err != nil {
		return "", fmt.Errorf("parse plist template: %w", err)
	}
	data := struct {
		Label      string
		BinaryPath string
		ConfigPath string
		SocketPath string
		GroupName  string
	}{
		Label:      launchdLabel,
		BinaryPath: html.EscapeString(opts.BinaryPath),
		ConfigPath: html.EscapeString(opts.ConfigPath),
		SocketPath: html.EscapeString(opts.SocketPath),
		GroupName:  html.EscapeString(opts.GroupName),
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render plist template: %w", err)
	}
	out := buf.String()
	out = strings.TrimRight(out, "\n") + "\n"
	return out, nil
}
