package service

// This file holds the systemd unit-file template and the helper that
// renders it. Kept separate from service_linux.go so that the template
// is reviewable in isolation — a unit file's clauses are conventions,
// not code, and they deserve to be read together.

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// unitTemplate is the canonical hsh-tunneld systemd unit. It is written
// to /etc/systemd/system/hsh-tunneld.service at install time.
//
// Design notes:
//
//   - Type=simple — the daemon does not double-fork or notify, it just
//     stays in the foreground until SIGTERM. simple is the right type
//     for that; notify would require us to call sd_notify which we do
//     not want to depend on.
//
//   - User=root — the daemon needs CAP_NET_ADMIN to create the TUN
//     device. We could grant the capability via AmbientCapabilities and
//     run as an unprivileged user, but then setting up routes
//     (UnconfigureRoutes/ConfigureRoutes inside tunnelmgr) would also
//     need CAP_NET_ADMIN at that point, and the netstack interaction
//     with the kernel routing table is best owned by root anyway. The
//     unit narrows what root is allowed to do via the hardening clauses
//     below — root in this unit cannot read /etc/passwd, /home, etc.
//
//   - RuntimeDirectory=hsh — systemd creates /run/hsh/ at activation
//     with mode 0750 and chowns it to root:{{.GroupName}}. The socket
//     and the control-token both live inside it, so a single declared
//     directory is enough.
//
//   - RuntimeDirectoryMode=0750 — owner=root (full), group={{.GroupName}}
//     (read+enter). World cannot list. We want the group to be able to
//     open the socket; 0750 is enough because connect(2) on a unix
//     socket only requires execute on the parent directory.
//
//   - ConfigurationDirectory=hsh — systemd creates /etc/hsh/ at
//     install time with mode 0750, root:{{.GroupName}}. config.toml
//     itself stays mode 0600 (written by the daemon) so only root can
//     read the bearer token. The group permission on the directory is
//     so that future "let the group read non-secret config" features
//     have headroom without re-chowning.
//
//   - ExecStartPre=...validate-config — fail fast on a malformed
//     config. systemd prints the validate-config stderr to the journal
//     so a bad config gives an actionable error before the daemon
//     tries to bring the netstack up.
//
//   - The hardening block (ProtectSystem, ProtectHome, …) follows the
//     recommendations of `systemd-analyze security`. We pick the
//     strictest set that still lets the daemon do its job:
//     ProtectSystem=strict + RuntimeDirectory + ConfigurationDirectory
//     gives us a system with everything read-only except the dirs we
//     declared. NoNewPrivileges blocks setuid binaries inside the
//     unit, which we have none of. RestrictAddressFamilies allows
//     AF_UNIX (for IPC), AF_INET / AF_INET6 (for gateway dial), and
//     AF_NETLINK (TUN/TAP and routing table). AF_PACKET is excluded —
//     we never sniff raw frames.
//
//   - We deliberately do NOT set SystemCallFilter. The Go runtime
//     uses a handful of newer syscalls (rseq, futex_waitv on recent
//     glibcs, getdents64) that drift between Go versions. Pinning a
//     SystemCallFilter that fits Go 1.26 today guarantees a SIGSYS
//     core-dump on Go 1.27 next year. We pay for that flexibility
//     with a slightly weaker seccomp surface; the other clauses
//     (ProtectSystem, CapabilityBoundingSet, RestrictAddressFamilies)
//     still keep the blast radius small. If we want SystemCallFilter
//     in the future the right path is to derive the set from a strace
//     of the running daemon, not from systemd's coarse filter groups.
//
//   - AmbientCapabilities is empty by default; we run as root so we
//     have everything. We do however add CAP_NET_ADMIN to
//     CapabilityBoundingSet so that we cannot regress into a state
//     where some future refactor uses additional caps without our
//     noticing.
//
//   - Restart=on-failure with RestartSec=2 — survives transient
//     gateway outages without flapping. We deliberately do NOT use
//     Restart=always because we want a deliberate `systemctl stop`
//     to actually stop the daemon (Restart=always would treat clean
//     exit-0 as a failure too).
//
// {{.SocketPath}} is the daemon's IPC socket — we propagate it as the
// --ipc-socket flag so the user can override the default at install
// time and have everything stay consistent.
const unitTemplate = `# hsh-tunneld systemd unit.
# Generated by 'hsh-tunneld install' — do not edit by hand. Run
# 'sudo hsh-tunneld install' again to refresh, or 'sudo hsh-tunneld
# uninstall' to remove.
[Unit]
Description=Hoop Tunnel daemon (hsh-tunneld)
Documentation=https://hoop.dev/docs/tunnel
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root

# Pre-flight: refuse to start if config is malformed. Stderr ends up
# in 'journalctl -u hsh-tunneld' with a useful diagnostic.
ExecStartPre={{.BinaryPath}} validate-config --config-file {{.ConfigPath}}

ExecStart={{.BinaryPath}} \
  --config-file {{.ConfigPath}} \
  --ipc-socket {{.SocketPath}} \
  --ipc-group {{.GroupName}}

# Reload-on-config-change is not supported by the daemon today; SIGHUP
# is reserved for a future hot-reload flow (RD-209). Don't advertise it
# until it's actually wired up.

Restart=on-failure
RestartSec=2

# Runtime directory (socket + token live here). systemd creates it,
# chowns it root:{{.GroupName}}, mode 0750, and removes it on stop.
RuntimeDirectory=hsh
RuntimeDirectoryMode=0750

# Config directory. Persists across stop/start (unlike RuntimeDirectory).
# The daemon writes config.toml with mode 0600 itself; we just own the
# parent dir.
ConfigurationDirectory=hsh
ConfigurationDirectoryMode=0750

# Group ownership of the runtime + config directories. Members of this
# group can read the control-token and connect to the IPC socket.
{{- if .GroupName }}
Group=root
SupplementaryGroups={{.GroupName}}
{{- end }}

# Hardening. See 'systemd-analyze security hsh-tunneld' for the score.
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectKernelLogs=yes
ProtectControlGroups=yes
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
PrivateTmp=yes
PrivateDevices=no
# Need RW access to /dev/net/tun for the TUN device; PrivateDevices=yes
# would hide it. Restrict the namespace explicitly instead.
DeviceAllow=/dev/net/tun rwm

LockPersonality=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RestrictNamespaces=yes
SystemCallArchitectures=native

# SystemCallFilter intentionally omitted — see unit_linux.go for rationale.

RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK

CapabilityBoundingSet=CAP_NET_ADMIN

# Standard output goes to the journal. Operators can follow it with
# 'journalctl -u hsh-tunneld -f'.
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
`

// renderUnit returns the rendered hsh-tunneld.service file body for
// the given Options. The caller is responsible for writing it to the
// filesystem; we keep rendering pure so tests can diff the output
// without touching disk.
//
// renderUnit returns an error only if the template parser itself
// fails, which never happens at runtime (the template is a compile-time
// constant) but is worth surfacing during development.
func renderUnit(opts Options) (string, error) {
	tmpl, err := template.New("hsh-tunneld.service").Parse(unitTemplate)
	if err != nil {
		return "", fmt.Errorf("parse unit template: %w", err)
	}
	data := struct {
		BinaryPath string
		ConfigPath string
		SocketPath string
		GroupName  string
	}{
		BinaryPath: opts.BinaryPath,
		ConfigPath: opts.ConfigPath,
		SocketPath: opts.SocketPath,
		GroupName:  opts.GroupName,
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render unit template: %w", err)
	}
	out := buf.String()
	// Normalise trailing whitespace: systemd is happy with either but
	// we want stable diffs across re-installs.
	out = strings.TrimRight(out, "\n") + "\n"
	return out, nil
}
