#!/usr/bin/env bash
#
# Writes the Vertex config and validates it without binding a port.
#
# -validate is the real credential test: it builds every lane AND mints one
# Vertex token, so a bad key, a missing roles/aiplatform.user binding or a
# skewed clock fails here rather than on the first risky statement in
# production.
#
# It also exercises the refusals, because a guardrail that loads and never
# fires is the failure this whole config surface exists to prevent. Each
# negative case below is a config that would otherwise look fine.
#
# The last two are the free-tier caps rather than a misconfiguration: this
# build enforces one guardrail rule and one data masking rule per process, and
# a cap nobody tests is a cap that stops firing.
#
# Usage:
#   HOOP_PROJECT=my-project ./01-validate.sh
#
# Costs nothing beyond one token mint.

set -uo pipefail
cd "$(dirname "$0")"
source ./lib.sh

[[ -n "$HOOP_PROJECT" ]] || die "set HOOP_PROJECT to your GCP project id"

h "Build the relay"
( cd ../../cmd && go build -o "$BIN" . ) || die "go build failed"
ok "built $BIN ($("$BIN" -version))"

# ------------------------------------------------------------------ config
h "Write the config"

cred_line=""
[[ -n "${HOOP_CREDENTIALS_FILE:-}" ]] && cred_line="  credentials_file: ${HOOP_CREDENTIALS_FILE}"

cat > "$CONFIG" <<YAML
# Generated by sidecar/scripts/dev/01-validate.sh. Edit the script, not this.
log_level: info

admin:
  listen: 127.0.0.1:${ADMIN_PORT}

audit:
  file: "-"                 # stdout as JSON lines; 03-verify.sh reads these
  memory_buffer: 256
  query_sessions: 500

pii:
  entities: [EMAIL_ADDRESS, US_SSN, BR_CPF]

analyzer:
  provider: vertex
  model: ${HOOP_MODEL}
  extra: {project: ${HOOP_PROJECT}, region: ${HOOP_REGION}}
${cred_line}
  timeout_sec: 20
  fail_open: true           # a vendor outage must not take the database down
  send: redacted            # the detector above withholds entity VALUES
  max_input_bytes: 8192
  cache: {size: 1024, ttl_sec: 900}
  max_calls: 50             # a ceiling for a test run, not a production number

guardrails:
  mode: enforce

listeners:
  - name: appdb
    protocol: postgres
    listen: 127.0.0.1:${PG_RELAY_PORT}
    upstream: 127.0.0.1:${PG_UPSTREAM_PORT}
    guardrails:
      rules:
        # Free, deterministic, and first in the chain: a DROP never reaches a
        # model, because Chain short-circuits on the first denial.
        - name: no-drops
          type: operation
          operations: [drop, truncate]
          message: schema changes are not permitted on appdb

        # The trigger excludes select, so read traffic costs nothing.
        - name: risky-writes
          type: ai_analysis
          trigger: {operations: [update, delete]}
          high: block
          medium: warn
          low: allow
          message: refused by risk analysis
          prompt: |
            You are classifying SQL against a production customer ledger.
            A DELETE or UPDATE with no WHERE clause is high risk. A write
            scoped by a primary key is low risk.

  - name: api
    protocol: http
    listen: 127.0.0.1:${HTTP_RELAY_PORT}
    upstream: 127.0.0.1:${HTTP_UPSTREAM_PORT}
    # Required. Without it the codec captures no body, the analyzer sees
    # "POST /anything" and nothing else, and every request is skipped. The
    # relay refuses this config at startup when it is missing.
    http:
      capture_body: true
      max_body_bytes: 8192
      headers: [Content-Type]
    guardrails:
      rules:
        - name: risky-payloads
          type: ai_analysis
          trigger: {resources: ["/anything"]}
          high: block
          medium: warn
          prompt: |
            You are classifying HTTP request bodies to an internal orders API.
            A payload that deletes or overwrites in bulk is high risk. An
            ordinary read or a single scoped write is low risk.
YAML
ok "wrote $CONFIG"

# -------------------------------------------------------------- the real test
h "Validate, which also mints a Vertex token"
note "A bad key, a missing IAM binding or a skewed clock fails HERE."

if ! out=$("$BIN" -validate -config "$CONFIG" 2>&1); then
    bad "validation failed"
    printf '\n%s\n\n' "$out"
    case "$out" in
        *"could not mint"*) die "The credential is the problem. Run ./00-preflight.sh to see
       whether Vertex is reachable at all from this machine." ;;
        *"readable by group or other"*) die "chmod 600 your credential file." ;;
        *"not linked"*) die "This binary was built without the vertex provider. Build from
       sidecar/cmd, which links all three." ;;
        *) die "See the message above." ;;
    esac
fi
printf '%s\n' "$out" | sed 's/^/  /'
ok "config valid and the Vertex credential mints"

# ------------------------------------------------------------- the refusals
# Each of these is a config that would otherwise load and do nothing.
h "Refusals: configs that look fine and would never fire"

refuse() {
    local label="$1" want="$2" edit="$3"
    python3 - "$CONFIG" "$WORKDIR/bad.yaml" "$edit" <<'PY'
import sys, re
src, dst, edit = sys.argv[1], sys.argv[2], sys.argv[3]
s = open(src).read()
if edit == "no-trigger":
    s = s.replace("          trigger: {operations: [update, delete]}\n", "")
elif edit == "no-capture":
    s = s.replace("      capture_body: true\n", "      capture_body: false\n")
elif edit == "negative-budget":
    s = s.replace("  max_calls: 50", "  max_calls: -1")
elif edit == "review":
    s = s.replace("          high: block\n          medium: warn\n          low: allow",
                  "          high: require_review\n          medium: warn\n          low: allow")
elif edit == "bad-provider":
    s = s.replace("  provider: vertex", "  provider: bedrock")
elif edit == "auth-header":
    s = s.replace("      headers: [Content-Type]", "      headers: [Content-Type, Authorization]")
elif edit == "second-guardrail":
    s = s.replace("        - name: no-drops\n",
                  "        - name: no-deletes\n"
                  "          type: operation\n"
                  "          operations: [delete]\n"
                  "          message: deletes are not permitted on appdb\n"
                  "        - name: no-drops\n")
elif edit == "two-mask-rules":
    s = s.replace("guardrails:\n  mode: enforce\n",
                  "guardrails:\n  mode: enforce\n\n"
                  "mask:\n  rules:\n"
                  "    - {name: ssn, entities: [US_SSN], strategy: redact}\n"
                  "    - {name: cpf, entities: [BR_CPF], strategy: redact}\n")
open(dst, "w").write(s)
PY
    local got
    got=$("$BIN" -validate -config "$WORKDIR/bad.yaml" 2>&1)
    if [[ "$got" == *"$want"* ]]; then
        ok "$label"
    else
        bad "$label -- expected a message containing: $want"
        printf '%s\n' "$got" | sed 's/^/        /'
        FAILED=1
    fi
}

FAILED=0
refuse "ai rule with no trigger"                "has no trigger"            no-trigger
refuse "http ai rule without capture_body"      "capture_body"              no-capture
refuse "negative max_calls"                     "max_calls is negative"     negative-budget
refuse "require_review, which this build cannot honor" "require_review"     review
refuse "a provider the binary does not link"    "not linked"                bad-provider
refuse "Authorization in the header allowlist"  "may not be exposed"        auth-header
refuse "a second guardrail rule"                "2 guardrail rules"         second-guardrail
refuse "a second data masking rule"             "2 data masking rules"      two-mask-rules
rm -f "$WORKDIR/bad.yaml"

[[ $FAILED -eq 0 ]] || die "a refusal did not fire. The config surface is not doing its job."

h "Validation passed"
note "Next: ./02-run.sh"
