# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# before:
  # hooks:
    # You may remove this if you don't use go modules.
    # - go mod tidy
builds:
  - id: hoop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
    - amd64
    - arm64
    main: ./client/main.go
    binary: hoop
    ldflags:
    - -s -w
    - -X github.com/runopsio/hoop/client/version.version={{ .Version }}
    - -X github.com/runopsio/hoop/client/version.gitCommit={{ .Commit }}
    - -X github.com/runopsio/hoop/client/version.buildDate={{ .Date }}
  - id: hoop-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
    - amd64
    - arm64
    main: ./agent/cmd/main.go
    binary: hoop-agent
    ldflags:
    - -s -w
    - -X github.com/runopsio/hoop/agent/version.version={{ .Version }}
    - -X github.com/runopsio/hoop/agent/version.gitCommit={{ .Commit }}
    - -X github.com/runopsio/hoop/agent/version.buildDate={{ .Date }}
  - id: hoop-gateway
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
    - amd64
    - arm64
    main: ./gateway/main.go
    binary: hoop-gateway
    ldflags:
    - -s -w
    - -X github.com/runopsio/hoop/gateway/version.version={{ .Version }}
    - -X github.com/runopsio/hoop/gateway/version.gitCommit={{ .Commit }}
    - -X github.com/runopsio/hoop/gateway/version.buildDate={{ .Date }}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
# release:
  # it will publish on a public repo
  # github:
  #   owner: runopsio
  #   name: hoop
dockers:
  - dockerfile: Dockerfile
    image_templates:
    - "runops/hoop:{{ .Tag }}"
    - "runops/hoop:latest"
    extra_files:
    - rootfs
# brews:
#   - tap:
#       owner: runopsio
#       name: hoop
#     url_template: "https://github.com/runopsio/hoop/releases/download/{{ .Version }}/{{ .ArtifactName }}"
#     commit_author:
#       name: runopsteam
#       email: team@runops.io
#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     homepage: "https://github.com/runopsio/hoop"
#     description: "Runops Proxy forwards remote tcp connections locally."
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-{{ .Prerelease }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
