FROM ubuntu:focal-20220801

ENV DEBIAN_FRONTEND=noninteractive
ENV ACCEPT_EULA=y
ARG CLOJURE_VERSION=1.10.3.1040

# Common
RUN mkdir -p /app && \
    mkdir -p /opt/hoop/sessions && \
    apt-get update -y && \
    apt-get install -y \
        locales \
        tini \
        apt-utils \
        curl \
        gnupg \
        gnupg2 \
        groff \
        jq \
        openssh-client \
        unzip \
        expect \
        lsb-release

# kubectl / aws-cli / aws-session-manager
RUN curl -sL "https://dl.k8s.io/release/v1.22.1/bin/linux/amd64/kubectl" -o kubectl && \
        echo '78178a8337fc6c76780f60541fca7199f0f1a2e9c41806bded280a4a5ef665c9  kubectl' | sha256sum -c --ignore-missing --strict - && \
        chmod 755 kubectl && \
        mv kubectl /usr/local/bin/kubectl && \
    curl -sL "https://s3.amazonaws.com/session-manager-downloads/plugin/1.2.245.0/ubuntu_64bit/session-manager-plugin.deb" -o session-manager-plugin.deb && \
        echo 'f1c03d2aaad9f89f73fc70f1c1cdef0e2877a03b86cca3c8b5c97992c6344449  session-manager-plugin.deb' | sha256sum -c --ignore-missing --strict - && \
        dpkg -i session-manager-plugin.deb && \
        rm -f /tmp/* session-manager-plugin.deb

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
    echo "deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list && \
    echo "deb https://cli-assets.heroku.com/apt ./" > /etc/apt/sources.list.d/heroku.list && \
    curl -sL https://cli-assets.heroku.com/apt/release.key | apt-key add - && \
    curl -sL https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list && \
    curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    curl -sL https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add - && \
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN apt-get update -y && \
    apt-get install -y \
        mongodb-mongosh mongodb-org-tools mongodb-org-shell \
        awscli \
        openjdk-11-jre \
        heroku \
        default-mysql-client \
        postgresql-client-15 \
        mssql-tools \
        unixodbc-dev && \
        rm -rf /var/lib/apt/lists/*

# clojure
RUN curl -sL https://download.clojure.org/install/linux-install-$CLOJURE_VERSION.sh -o clojure-install.sh && \
    sha256sum clojure-install.sh && \
    echo "665e35e8d7dd0996edaba36220fd5048fee95f5155ec0426f628f18770239821 clojure-install.sh" | sha256sum -c - && \
    bash clojure-install.sh && \
    rm clojure-install.sh && \
    clojure -e "(clojure-version)"

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8

ENV PATH="/opt/mssql-tools/bin:/app:${PATH}"

COPY rootfs /

EXPOSE 8009
EXPOSE 8010

ENTRYPOINT ["tini", "--", "/app/entrypoint.sh"]
