(ns webapp.env)

(goog-define release-type "")
(goog-define api-url "")
(goog-define segment-write-key "")
(goog-define sentry-sample-rate "")
(goog-define sentry-dsn "")
(goog-define hoop-app-url "")
(goog-define webapp-url "")
(goog-define canny-id "")
