import {
  Package,
  LayoutDashboard,
  SquareCode,
  BookUp2,
  GalleryVerticalEnd,
  Inbox,
  CircleCheckBig,
  BookMarked,
  ShieldCheck,
  VenetianMask,
  UserRoundCheck,
  PackageSearch,
  BrainCog,
  Puzzle,
  Settings,
  Users,
} from 'lucide-react'

export const NAVIGATION_ACTIONS = [
  { id: 'resources',          label: 'Resources',          description: 'Manage resources',                group: 'Navigation',   icon: Package,            path: '/resources' },
  { id: 'dashboard',          label: 'Dashboard',          description: 'Overview dashboard',              group: 'Navigation',   icon: LayoutDashboard,    path: '/dashboard' },
  { id: 'terminal',           label: 'Terminal',           description: 'Open terminal',                   group: 'Navigation',   icon: SquareCode,         path: '/client' },
  { id: 'runbooks',           label: 'Runbooks',           description: 'Browse and run runbooks',         group: 'Navigation',   icon: BookUp2,            path: '/runbooks' },
  { id: 'sessions',           label: 'Sessions',           description: 'View session history',            group: 'Navigation',   icon: GalleryVerticalEnd, path: '/sessions' },
  { id: 'reviews',            label: 'Reviews',            description: 'Review access requests',          group: 'Navigation',   icon: Inbox,              path: '/reviews' },

  { id: 'access-request',     label: 'Access Request',     description: 'Manage access requests',          group: 'Discover',     icon: CircleCheckBig,     path: '/features/access-request' },
  { id: 'runbooks-setup',     label: 'Runbooks Setup',     description: 'Configure runbooks',              group: 'Discover',     icon: BookMarked,         path: '/features/runbooks/setup' },
  { id: 'guardrails',         label: 'Guardrails',         description: 'Configure guardrails',            group: 'Discover',     icon: ShieldCheck,        path: '/guardrails' },
  { id: 'data-masking',       label: 'AI Data Masking',    description: 'Configure AI data masking',       group: 'Discover',     icon: VenetianMask,       path: '/features/data-masking' },
  { id: 'access-control',     label: 'Access Control',     description: 'Manage access control rules',     group: 'Discover',     icon: UserRoundCheck,     path: '/features/access-control' },
  { id: 'resource-discovery', label: 'Resource Discovery', description: 'Discover resources automatically', group: 'Discover',    icon: PackageSearch,      path: '/integrations/aws-connect' },

  { id: 'agents',             label: 'Agents',             description: 'Manage agents',                   group: 'Organization', icon: BrainCog,           path: '/agents' },
  { id: 'authentication',     label: 'Authentication',     description: 'Configure authentication',        group: 'Organization', icon: Puzzle,             path: '/integrations/authentication' },
  { id: 'jira',               label: 'Jira',               description: 'Configure Jira integration',      group: 'Organization', icon: Puzzle,             path: '/settings/jira' },
  { id: 'settings-infra',     label: 'Infrastructure',     description: 'Infrastructure settings',         group: 'Organization', icon: Settings,           path: '/settings/infrastructure' },
  { id: 'license',            label: 'License',            description: 'License management',              group: 'Organization', icon: Settings,           path: '/settings/license' },
  { id: 'users',              label: 'Users',              description: 'Manage organization users',       group: 'Organization', icon: Users,              path: '/organization/users' },
]
