config:
  ORG_MULTI_TENANT: 'false'
  POSTGRES_DB_URI: "${HOOP_SELF_HOSTED_TRYRUNOPS_POSTGRES_DB_URI}"
  PGREST_ROLE: 'hoop_apiuser_tryrunops'
  LOG_LEVEL: 'info'
  API_URL: 'https://tryrunops.hoop.dev'
  IDP_URI: "https://${HOOP_SELF_HOSTED_TRYRUNOPS_IDP_CLIENT_ID}:${HOOP_SELF_HOSTED_TRYRUNOPS_IDP_CLIENT_SECRET}@hoophq.us.auth0.com/"
  IDP_AUDIENCE: 'https://hoophq.us.auth0.com/api/v2/'
  ASK_AI_CREDENTIALS: '${HOOP_SELF_HOSTED_TRYRUNOPS_ASK_AI_CREDENTIALS}'
  GOOGLE_APPLICATION_CREDENTIALS_JSON: '${GOOGLE_APPLICATION_CREDENTIALS_JSON}'
  WEBHOOK_APPKEY: "${HOOP_SELF_HOSTED_TRYRUNOPS_WEBHOOK_APPKEY}"
  PLUGIN_AUDIT_PATH: '/opt/hoop/sessions'
  PLUGIN_INDEX_PATH: '/opt/hoop/sessions/indexes'
  PLUGIN_REGISTRY_URL: 'https://pluginregistry.s3.amazonaws.com/packages.json'

persistence:
  # -- Use persistent volume for write ahead log sessions
  enabled: true
  storageClassName: gp2

  # -- Size of persistent volume claim
  size: 10Gi

ingressApi:
  enabled: true
  host: tryrunops.hoop.dev
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:200074533906:certificate/9e0fee17-7fbc-45bd-bc7d-da19ea9cddd4
    alb.ingress.kubernetes.io/group.name: tryrunopsgroup
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip

ingressGrpc:
  enabled: true
  host: tryrunops.hoop.dev
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:200074533906:certificate/9e0fee17-7fbc-45bd-bc7d-da19ea9cddd4
    alb.ingress.kubernetes.io/group.name: tryrunopsgroup
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

# -- CPU/Memory resource requests/limits
resources:
  gw:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 512Mi
