{{- with .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoopcontrolplane.extraSecretName" $ }}
  labels:
    {{- include "hoopcontrolplane.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $KEY, $VAL := . }}
  {{ $KEY }}: '{{ $VAL }}'
  {{- end }}
{{- end }}
