apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoopcontrolplane.configSecretName" . }}
  labels:
    {{- include "hoopcontrolplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB_URI: {{ required "config.POSTGRES_DB_URI is required" .Values.config.POSTGRES_DB_URI | quote }}
  API_URL: {{ required "config.API_URL is required" .Values.config.API_URL | quote }}

  {{- if .Values.config.IDP_ISSUER }}
  IDP_ISSUER: {{ .Values.config.IDP_ISSUER | quote }}
  IDP_CLIENT_ID: {{ required "config.IDP_CLIENT_ID is required when config.IDP_ISSUER is set" .Values.config.IDP_CLIENT_ID | quote }}
  IDP_CLIENT_SECRET: {{ required "config.IDP_CLIENT_SECRET is required when config.IDP_ISSUER is set" .Values.config.IDP_CLIENT_SECRET | quote }}
  IDP_CUSTOM_SCOPES: {{ .Values.config.IDP_CUSTOM_SCOPES | default "" | quote }}
  IDP_GROUPS_CLAIM: {{ .Values.config.IDP_GROUPS_CLAIM | default "" | quote }}
  {{- end }}
  IDP_AUDIENCE: {{ .Values.config.IDP_AUDIENCE | default "" | quote }}

  MIGRATION_PATH_FILES: {{ .Values.config.MIGRATION_PATH_FILES | default "" | quote }}
  GIN_MODE: {{ .Values.config.GIN_MODE | default "release" | quote }}
  LOG_ENCODING: {{ .Values.config.LOG_ENCODING | default "json" | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | default "info" | quote }}

  TLS_CERT: {{ .Values.config.TLS_CERT | default "" | quote }}
  TLS_KEY: {{ .Values.config.TLS_KEY | default "" | quote }}
