{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoopcontrolplane.fullname" . }}
  labels:
    {{- include "hoopcontrolplane.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "hoopcontrolplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ include "hoopcontrolplane.httpPort" . }}
      targetPort: {{ include "hoopcontrolplane.httpPort" . }}
      protocol: TCP
{{- end }}
