blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/rogefm/hoop/wiki
    about: Check out our documentation for guides and tutorials
  - name: 💬 Discussions
    url: https://github.com/rogefm/hoop/discussions
    about: Join our community discussions for general questions and ideas
  - name: 🚨 Security Issues
    url: https://github.com/rogefm/hoop/security/policy
    about: Please report security vulnerabilities privately 
