blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://hoop.dev/docs
    about: Check out our documentation for guides and tutorials
  - name: 💬 Discussions
    url: https://github.com/hoophq/hoop/discussions
    about: Join our community discussions for general questions and ideas
