{{- if and .Values.gatewayApi.enabled .Values.gatewayApi.createGateway -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayApi.gateway.name }}
  {{- with .Values.gatewayApi.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gatewayApi.gateway.gatewayClassName }}
  listeners:
    {{- toYaml .Values.gatewayApi.gateway.listeners | nindent 4 }}
  {{- with .Values.gatewayApi.gateway.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gatewayApi.gateway.infrastructure }}
  infrastructure:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gatewayApi.gateway.backendTLS }}
  backendTLS:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
