{{- if .Values.ingressGrpc.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- with .Values.ingressGrpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: hoopgateway-grpc
  name: hoopgateway-grpc
spec:
  ingressClassName: {{ required "ingressGrpc.ingressClassName is required" .Values.ingressGrpc.ingressClassName | quote }}
  rules:
  - host: {{ .Values.ingressGrpc.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: hoopgateway
            port:
              number: 8010
        pathType: ImplementationSpecific
  {{- with .Values.ingressGrpc.tls }}
  tls:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}