{{- if and .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: walsessions
  {{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
    - 'ReadWriteOnce'
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ required "persistence.storageClassName is required" .Values.persistence.storageClassName }}
{{ end -}}