{{- if .Values.defaultAgentSpiffe.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
data:
  helper.conf: |
    agent_address = "{{ .Values.defaultAgentSpiffe.spiffeHelper.agentAddress | default "/spiffe-workload-api/spire-agent.sock" }}"
    cmd = ""
    cert_dir = ""
    svid_file_name = ""
    svid_key_file_name = ""
    svid_bundle_file_name = ""
    jwt_svids = [
      {
        jwt_audience       = "{{ required "defaultAgentSpiffe.spiffeHelper.audience is required when defaultAgentSpiffe.enabled=true" .Values.defaultAgentSpiffe.spiffeHelper.audience }}"
        jwt_svid_file_name = "/run/spiffe/agent.jwt"
      }
    ]
{{- end }}
