import { useEffect } from 'react'
import { Group, List, Stack, Text } from '@mantine/core'
import { KeyRound } from 'lucide-react'
import Alert from '@/components/Alert'
import Badge from '@/components/Badge'
import Button from '@/components/Button'
import CopyButton from '@/components/CopyButton'
import SectionRow from '@/components/SectionRow'
import TextInput from '@/components/TextInput'
import { showSnackbar } from '@/utils/snackbar'
import { useProvisioningStore } from '../store'

function formatDate(value) {
  return value ? new Date(value).toLocaleString() : 'never'
}

// SCIM: the identity provider pushes users and groups with a bearer token.
export default function ScimSection({ disabled }) {
  const scim = useProvisioningStore((s) => s.scim)
  const newToken = useProvisioningStore((s) => s.newToken)
  const saving = useProvisioningStore((s) => s.saving)
  const generateToken = useProvisioningStore((s) => s.generateToken)
  const deleteToken = useProvisioningStore((s) => s.deleteToken)
  const clearNewToken = useProvisioningStore((s) => s.clearNewToken)

  // The token is shown once, to the view that generated it.
  useEffect(() => clearNewToken, [clearNewToken])

  async function handleGenerate() {
    const { ok, error } = await generateToken()
    if (!ok) showSnackbar({ level: 'error', text: 'Failed to generate the SCIM token.', description: error })
  }

  async function handleDelete() {
    const { ok, error } = await deleteToken()
    if (ok) showSnackbar({ level: 'success', text: 'SCIM token revoked.' })
    else showSnackbar({ level: 'error', text: 'Failed to revoke the SCIM token.', description: error })
  }

  return (
    <Stack gap="xl">
      <SectionRow
        title="SCIM endpoint"
        badge={
          <Badge variant={scim?.enabled ? 'active' : 'inactive'}>
            {scim?.enabled ? 'Enabled' : 'Disabled'}
          </Badge>
        }
        description="Okta, Entra ID, OneLogin, JumpCloud and Ping push users and groups here. Assign the Hoop app to the groups of your reviewers."
      >
        <Stack gap="md">
          <TextInput
            label="SCIM base URL"
            value={scim?.base_url ?? ''}
            readOnly
            rightSection={<CopyButton value={scim?.base_url ?? ''} label="Copy URL" />}
          />
          {scim?.enabled && (
            <Text size="sm" c="dimmed">
              {`Token generated by ${scim.created_by || 'an admin'} on ${formatDate(scim.created_at)}. Last used: ${formatDate(scim.last_used_at)}.`}
            </Text>
          )}
          {newToken && (
            <Alert color="yellow" variant="light" icon={<KeyRound size={16} />} radius="md">
              <Stack gap="xs">
                <Text size="sm">Copy the token now. It is not shown again.</Text>
                <TextInput value={newToken} readOnly rightSection={<CopyButton value={newToken} label="Copy token" />} />
              </Stack>
            </Alert>
          )}
          <Group justify="flex-end" gap="sm">
            {scim?.enabled && (
              <Button variant="outline" color="red" onClick={handleDelete} loading={saving}>
                Revoke token
              </Button>
            )}
            <Button onClick={handleGenerate} loading={saving} disabled={disabled}>
              {scim?.enabled ? 'Rotate token' : 'Generate token'}
            </Button>
          </Group>
        </Stack>
      </SectionRow>

      <SectionRow title="Setup" description="Configure the app in your identity provider with the URL and token above.">
        <List size="sm" spacing="xs">
          <List.Item>
            Okta: create a SCIM 2.0 app with HTTP header authentication, enable Push New Users, Push
            Profile Updates and Push Groups.
          </List.Item>
          <List.Item>
            Entra ID: in the enterprise application, set Provisioning to Automatic with the URL as Tenant
            URL and the token as Secret Token.
          </List.Item>
          <List.Item>
            Users are matched by email. A user who already signed in is taken over, not duplicated.
          </List.Item>
          <List.Item>A group named like a hoop group (admin, auditor, approver) is refused.</List.Item>
        </List>
      </SectionRow>
    </Stack>
  )
}
