package log

import (
	"strings"

	"log"
)

type httpLogger struct {
	logger *log.Logger
}

func (l *httpLogger) Write(p []byte) (n int, err error) {
	s := string(p)

	// ignore health check errors in the http server
	if strings.HasSuffix(s, "EOF\n") {
		return len(p), nil
	}
	Infof(strings.TrimSuffix(string(p), "\n"))
	return len(s), nil
}

// NewStdHttpLogger returns a custom logger for http.Server that filters out
// EOF errors commonly generated by health check probes.
func NewStdHttpLogger() *log.Logger {
	return log.New(&httpLogger{logger: log.Default()}, "", log.Llongfile)
}
