config:
  ORG_MULTI_TENANT: ''
  POSTGRES_DB_URI: '${HOOP_SELF_HOSTED_UNICO_POSTGRES_DB_URI}'
  PGREST_ROLE: 'hoop_apiuser_unico'
  API_URL: 'https://unico.hoop.dev'
  IDP_ISSUER: 'https://oauth.id.jumpcloud.com/'
  IDP_CLIENT_ID: '${HOOP_SELF_HOSTED_UNICO_IDP_CLIENT_ID}'
  IDP_CLIENT_SECRET: '${HOOP_SELF_HOSTED_UNICO_IDP_CLIENT_SECRET}'
  IDP_CUSTOM_SCOPES: ''
  IDP_AUDIENCE: ''
  GOOGLE_APPLICATION_CREDENTIALS_JSON: '${GOOGLE_APPLICATION_CREDENTIALS_JSON}'
  WEBHOOK_APPKEY: '${HOOP_SELF_HOSTED_UNICO_WEBHOOK_APPKEY}'
  PYROSCOPE_AUTH_TOKEN: ''
  PYROSCOPE_INGEST_URL: ''
  ADMIN_USERNAME: '[HOOP] Admin'
  PLUGIN_AUDIT_PATH: '/opt/hoop/sessions'
  PLUGIN_INDEX_PATH: '/opt/hoop/sessions/indexes'
  PLUGIN_REGISTRY_URL: 'https://pluginregistry.s3.amazonaws.com/packages.json'
  MAGIC_BELL_API_KEY: ''
  MAGIC_BELL_API_SECRET: ''

persistence:
  # -- Use persistent volume for write ahead log sessions
  enabled: true
  storageClassName: gp2

  # -- Size of persistent volume claim
  size: 100Gi

ingressApi:
  enabled: true
  host: unico.hoop.dev
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:200074533906:certificate/ef0cc68c-b2f5-4e84-bd2f-4a1d9eb63c7c
    alb.ingress.kubernetes.io/group.name: unicogroup
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip

ingressGrpc:
  enabled: true
  host: unico.hoop.dev
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:200074533906:certificate/ef0cc68c-b2f5-4e84-bd2f-4a1d9eb63c7c
    alb.ingress.kubernetes.io/group.name: unicogroup
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

# -- CPU/Memory resource requests/limits
resources:
  gw:
    limits:
      cpu: 2048m
      memory: 4Gi
    requests:
      cpu: 1024m
      memory: 4Gi
