package upgrade

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
)

func TestParseChecksums(t *testing.T) {
	content := `# generated by build pipeline
b570daadf2bec229f1d6e814bb58fa09b4475c40ba87bd98ad70ea58cc6c8f8d  hoop_1.72.0_Darwin_x86_64.tar.gz
3874f853c7ecc9510002f018c99d473b5f30a944d3552b709815d16fcdd970b3  hoop_1.72.0_Darwin_arm64.tar.gz
afa4e7bd329bc5d4d703fb7a6faba23e125f53acf3df9081f5d1f183f79c5283  *hoop_1.72.0_Linux_x86_64.tar.gz
`
	cases := map[string]string{
		"hoop_1.72.0_Darwin_x86_64.tar.gz": "b570daadf2bec229f1d6e814bb58fa09b4475c40ba87bd98ad70ea58cc6c8f8d",
		"hoop_1.72.0_Darwin_arm64.tar.gz":  "3874f853c7ecc9510002f018c99d473b5f30a944d3552b709815d16fcdd970b3",
		"hoop_1.72.0_Linux_x86_64.tar.gz":  "afa4e7bd329bc5d4d703fb7a6faba23e125f53acf3df9081f5d1f183f79c5283",
	}
	for name, want := range cases {
		got, ok := parseChecksums(content, name)
		if !ok {
			t.Fatalf("parseChecksums missed %s", name)
		}
		if got != want {
			t.Fatalf("parseChecksums(%s)=%s want %s", name, got, want)
		}
	}
	if _, ok := parseChecksums(content, "missing.tar.gz"); ok {
		t.Fatalf("expected miss for missing.tar.gz")
	}
}

func TestExtractHoopBinary(t *testing.T) {
	dir := t.TempDir()
	tarballPath := filepath.Join(dir, "hoop.tar.gz")
	binaryContent := []byte("\x7fELFfake-hoop-binary\n")
	writeTarball(t, tarballPath, map[string][]byte{
		"hoop":           binaryContent,
		"README.md":      []byte("ignored"),
		"docs/inner.txt": []byte("nested ignored"),
	})

	dst := filepath.Join(dir, "hoop")
	if err := extractHoopBinary(tarballPath, dst, "hoop"); err != nil {
		t.Fatalf("extractHoopBinary failed: %v", err)
	}
	got, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("read extracted binary: %v", err)
	}
	if !bytes.Equal(got, binaryContent) {
		t.Fatalf("extracted content mismatch: got %q want %q", got, binaryContent)
	}
}

// TestExtractHoopBinaryWindows guards the Windows release layout: the
// tarball carries hoop.exe (Go appends .exe for GOOS=windows), so the
// extractor must match that name rather than the bare "hoop".
func TestExtractHoopBinaryWindows(t *testing.T) {
	dir := t.TempDir()
	tarballPath := filepath.Join(dir, "hoop-win.tar.gz")
	binaryContent := []byte("MZ\x90\x00fake-windows-binary")
	writeTarball(t, tarballPath, map[string][]byte{
		"hoop.exe":  binaryContent,
		"README.md": []byte("ignored"),
	})

	dst := filepath.Join(dir, "hoop.exe")
	if err := extractHoopBinary(tarballPath, dst, "hoop.exe"); err != nil {
		t.Fatalf("extractHoopBinary(windows) failed: %v", err)
	}
	got, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("read extracted binary: %v", err)
	}
	if !bytes.Equal(got, binaryContent) {
		t.Fatalf("extracted content mismatch: got %q want %q", got, binaryContent)
	}

	// The Unix name must NOT match a Windows artifact.
	if err := extractHoopBinary(tarballPath, dst, "hoop"); err == nil {
		t.Fatalf("expected miss when looking for bare 'hoop' inside a Windows tarball")
	}
}

func TestExtractHoopBinaryMissing(t *testing.T) {
	dir := t.TempDir()
	tarballPath := filepath.Join(dir, "no-hoop.tar.gz")
	writeTarball(t, tarballPath, map[string][]byte{
		"README.md": []byte("nothing useful here"),
	})
	err := extractHoopBinary(tarballPath, filepath.Join(dir, "out"), "hoop")
	if err == nil {
		t.Fatalf("expected error when no hoop binary inside tarball")
	}
}

func TestInstallerEndToEnd(t *testing.T) {
	binaryContent := []byte("fake-hoop-binary-v1.99.0")
	tarball := buildTarball(t, map[string][]byte{"hoop": binaryContent})
	sum := sha256Hex(tarball)

	mux := http.NewServeMux()
	version := "1.99.0"
	platform := Platform{OS: "Darwin", Arch: "arm64"}
	artifactName := ArtifactName(version, platform)
	mux.HandleFunc("/release/"+version+"/checksums.txt", func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprintf(w, "%s  %s\n", sum, artifactName)
	})
	mux.HandleFunc("/release/"+version+"/"+artifactName, func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write(tarball)
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	home := t.TempDir()
	layout := LayoutFromHome(home)
	store := &Store{}
	inst := &Installer{
		Layout:  layout,
		Client:  srv.Client(),
		BaseURL: srv.URL + "/release",
	}

	entry, err := inst.Install(version, platform, store)
	if err != nil {
		t.Fatalf("Install: %v", err)
	}
	if entry.Version != version {
		t.Fatalf("entry version=%s want %s", entry.Version, version)
	}
	if entry.SHA256 != sum {
		t.Fatalf("entry sha=%s want %s", entry.SHA256, sum)
	}

	got, err := os.ReadFile(layout.VersionBinary(version))
	if err != nil {
		t.Fatalf("read installed binary: %v", err)
	}
	if !bytes.Equal(got, binaryContent) {
		t.Fatalf("installed binary mismatch")
	}

	// Re-installing should be a no-op (binary already present).
	entry2, err := inst.Install(version, platform, store)
	if err != nil {
		t.Fatalf("second Install: %v", err)
	}
	if entry2.Version != version {
		t.Fatalf("second install entry version=%s", entry2.Version)
	}
}

// TestInstallerWindowsArtifact exercises the full download+extract path
// against a Windows release artifact (which contains hoop.exe). It is the
// regression test for the bug where `hoop versions install` on Windows
// failed with "hoop binary not found inside ...tar.gz" because the
// extractor only ever looked for the bare name "hoop".
func TestInstallerWindowsArtifact(t *testing.T) {
	binaryContent := []byte("MZ\x90\x00fake-windows-binary-v1.99.0")
	tarball := buildTarball(t, map[string][]byte{"hoop.exe": binaryContent})
	sum := sha256Hex(tarball)

	version := "1.99.0"
	platform := Platform{OS: "Windows", Arch: "x86_64"}
	artifactName := ArtifactName(version, platform)

	mux := http.NewServeMux()
	mux.HandleFunc("/release/"+version+"/checksums.txt", func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprintf(w, "%s  %s\n", sum, artifactName)
	})
	mux.HandleFunc("/release/"+version+"/"+artifactName, func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write(tarball)
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	layout := LayoutFromHome(t.TempDir())
	store := &Store{}
	inst := &Installer{Layout: layout, Client: srv.Client(), BaseURL: srv.URL + "/release"}

	entry, err := inst.Install(version, platform, store)
	if err != nil {
		t.Fatalf("Install(windows): %v", err)
	}
	got, err := os.ReadFile(layout.VersionBinary(version))
	if err != nil {
		t.Fatalf("read installed binary: %v", err)
	}
	if !bytes.Equal(got, binaryContent) {
		t.Fatalf("installed binary mismatch")
	}
	if entry.SHA256 != sum {
		t.Fatalf("entry sha=%s want %s", entry.SHA256, sum)
	}
}

func TestInstallerChecksumMismatch(t *testing.T) {
	tarball := buildTarball(t, map[string][]byte{"hoop": []byte("payload")})
	mux := http.NewServeMux()
	version := "9.9.9"
	platform := Platform{OS: "Linux", Arch: "x86_64"}
	mux.HandleFunc("/release/"+version+"/checksums.txt", func(w http.ResponseWriter, _ *http.Request) {
		fmt.Fprintf(w, "%s  %s\n", "0000000000000000000000000000000000000000000000000000000000000000", ArtifactName(version, platform))
	})
	mux.HandleFunc("/release/"+version+"/"+ArtifactName(version, platform), func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write(tarball)
	})
	srv := httptest.NewServer(mux)
	defer srv.Close()

	layout := LayoutFromHome(t.TempDir())
	store := &Store{}
	inst := &Installer{Layout: layout, Client: srv.Client(), BaseURL: srv.URL + "/release"}
	if _, err := inst.Install(version, platform, store); err == nil {
		t.Fatalf("expected checksum mismatch error")
	}
	if _, err := os.Stat(layout.VersionBinary(version)); err == nil {
		t.Fatalf("binary should not be installed on checksum mismatch")
	}
}

// buildTarball returns the bytes of a gzip+tar archive containing the
// given files (relative paths -> content).
func buildTarball(t *testing.T, files map[string][]byte) []byte {
	t.Helper()
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gz)
	for name, body := range files {
		hdr := &tar.Header{
			Name:     name,
			Mode:     0755,
			Size:     int64(len(body)),
			Typeflag: tar.TypeReg,
		}
		if err := tw.WriteHeader(hdr); err != nil {
			t.Fatalf("tar header %s: %v", name, err)
		}
		if _, err := tw.Write(body); err != nil {
			t.Fatalf("tar write %s: %v", name, err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tar close: %v", err)
	}
	if err := gz.Close(); err != nil {
		t.Fatalf("gzip close: %v", err)
	}
	return buf.Bytes()
}

func writeTarball(t *testing.T, path string, files map[string][]byte) {
	t.Helper()
	data := buildTarball(t, files)
	if err := os.WriteFile(path, data, 0600); err != nil {
		t.Fatalf("write tarball: %v", err)
	}
}

func sha256Hex(b []byte) string {
	h := sha256.New()
	_, _ = io.Copy(h, bytes.NewReader(b))
	return hex.EncodeToString(h.Sum(nil))
}
