package analytics

const (
	EventLogin  = "hoop-login"
	EventSignup = "hoop-signup"

	EventFetchUsers             = "hoop-fetch-users"
	EventUpdateUser             = "hoop-update-user"
	EventCreateInvitedUser      = "hoop-create-invited-user"
	EventCreateConnection       = "hoop-create-connection"
	EventCreateServiceAccount   = "hoop-create-serviceaccount"
	EventUpdateServiceAccount   = "hoop-update-serviceaccount"
	EventUpdateConnection       = "hoop-update-connection"
	EventDeleteConnection       = "hoop-delete-connection"
	EventFetchConnections       = "hoop-fetch-connections"
	EventApiExecConnection      = "hoop-api-exec-connection"
	EventApiProxymanagerConnect = "hoop-api-proxymanager-connect"
	EventCreateAgent            = "hoop-create-agent"
	EventCreateStandardAgent    = "hoop-create-standard-agent"
	EventCreateEmbeddedAgent    = "hoop-create-embedded-agent"
	EventDeleteAgent            = "hoop-delete-agent"
	EventCreatePlugin           = "hoop-create-plugin"
	EventUdpatePlugin           = "hoop-udpate-plugin"
	EventUdpatePluginConfig     = "hoop-udpate-plugin-config"
	EventApiExecSession         = "hoop-api-exec-session"
	EventFetchSessions          = "hoop-fetch-sessions"
	EventListRunbooks           = "hoop-list-runbooks"
	EventExecRunbook            = "hoop-exec-runbook"
	EventUpdateReview           = "hoop-update-review"
	EventFetchReviews           = "hoop-fetch-reviews"
	EventApiExecReview          = "hoop-api-exec-review"
	EventSearch                 = "hoop-search"
	EventCreateClientKey        = "hoop-create-clientkey"
	EventFetchClientKey         = "hoop-fetch-clientkey"
	EventUpdateClientKey        = "hoop-update-clientkey"
	EventDeleteClientKey        = "hoop-delete-clientkey"
	EventOpenWebhooksDashboard  = "hoop-open-webhooks-dashboard"

	EventGrpcExec                = "hoop-grpc-exec"
	EventGrpcConnect             = "hoop-grpc-connect"
	EventGrpcProxyManagerConnect = "hoop-grpc-proxy-manager-connect"
)
