#!/bin/bash
set -euo pipefail

: "${1:? Missing dist folder! $0 <dist-folder> <version>}}"
: "${2:? Missing version! $0 <version> <checksum>}}"

DIST_FOLDER=$1
VERSION=$2

DARWIN_AMD64_CHECKSUM=$(cat ${DIST_FOLDER}/binaries/hoop_${VERSION}_Darwin_amd64_checksum.txt | awk {'print $1'})
DARWIN_ARM64_CHECKSUM=$(cat ${DIST_FOLDER}/binaries/hoop_${VERSION}_Darwin_arm64_checksum.txt | awk {'print $1'})
LINUX_AMD64_CHECKSUM=$(cat ${DIST_FOLDER}/binaries/hoop_${VERSION}_Linux_amd64_checksum.txt | awk {'print $1'})
LINUX_ARM64_CHECKSUM=$(cat ${DIST_FOLDER}/binaries/hoop_${VERSION}_Linux_arm64_checksum.txt | awk {'print $1'})

cat - <<EOF
# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoopcli"
  version "$VERSION"

  on_macos do
    if Hardware::CPU.intel?
      url "https://hoopartifacts.s3.amazonaws.com/release/$VERSION/hoop_${VERSION}_Darwin_amd64.tar.gz"
      sha256 "$DARWIN_AMD64_CHECKSUM"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://hoopartifacts.s3.amazonaws.com/release/$VERSION/hoop_${VERSION}_Darwin_arm64.tar.gz"
      sha256 "$DARWIN_ARM64_CHECKSUM"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://hoopartifacts.s3.amazonaws.com/release/$VERSION/hoop_${VERSION}_Linux_arm64.tar.gz"
      sha256 "$LINUX_AMD64_CHECKSUM"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://hoopartifacts.s3.amazonaws.com/release/$VERSION/hoop_${VERSION}_Linux_amd64.tar.gz"
      sha256 "$LINUX_ARM64_CHECKSUM"

      def install
        bin.install "hoop"
      end
    end
  end
end
EOF