{{- with .Values.extraSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: extra-agent-config
type: Opaque
stringData:
  {{- range $KEY, $VAL := . }}
  {{ $KEY }}: '{{ $VAL}}'
  {{- end }}
{{- end }}
